### ISSUE TITLE
[環境構築] CssのFix

### ISSUE THREAD

**Issue by bokusunny** [Motonary/Fortuna#31]
## 概要
なぜかOrbitと同じ設定にしたのにCssが読み込めないのでFixする
~Css modulesをdemoコンポーネントに適用させる~
## 詳細
extract-text-webpack-pluginはWebpack4では推奨されないのでmini-css-extract-pluginに移行したい。 ref) https://github.com/webpack-contrib/extract-text-webpack-plugin#usage

**Comment by rechtburg** [comment]
@bokusunny 
これCSS読み込めないって結構クリティカルだから別issueでASAPでできないかな？

**Comment by bokusunny** [comment]
Issueは直接書き換えるのではなく改善案をコメントして欲しいな
> そもそもWebpack.confing.jsのloaderの恒星も知識ない時にコピペしたものなのでちゃんと理解して最適化したい

これとかなぜ消した？

**Comment by rechtburg** [comment]
Issue分けたから重複する内容を２つ書いたら混乱するかと

**Comment by bokusunny** [comment]
理解した
> Issueは直接書き換えるのではなく改善案をコメントして欲しい

これ今後よろしく

**Comment by rechtburg** [comment]
申し訳ない。
あと、issueに関してなんですが、
issueってメモではなく、本質的にある種の要件定義、外部仕様書に近いものだと思うので
したいとか、学ぶ云々ではなく、タイトルの事項に対して、どういう背景とか機能で、
なにを実装するか、何をする必要があるのかを端的に書く方がいいかなと思う

**Comment by bokusunny** [comment]
了解しました！
これも共通認識としてドキュメント化したいんだけど、どこに書くのがいいかな？

**Comment by rechtburg** [comment]
エンジニアGeneralでいいと思う！
