### ISSUE TITLE
[環境構築] webpack / loaderの最適化 + Css Modulesの導入

### ISSUE THREAD

**Issue by rechtburg** [Motonary/Fortuna#34]
## 背景
Webpack.confing.jsのloaderの恒星も知識ない時にコピペしたものなのでちゃんと理解して最適化したい

## 詳細
- [x] loader周りの最適化
- [x] Css　Moduleの導入

**Comment by bokusunny** [comment]
## loader周りの調査結果
**結論: このままの構成でいこうと思います**
- css
cssをwebpackでバンドルするならcss-loader + mini-css-extract-plaginが王道
- image(file-loader vs css-loader)
url-loaderとfile-loaderどちらでも大差ないっぽいのでこのままfile-loaderで行こうと思います
- typescript(ts-loader vs awesome-typescript-loader)
awsome-ts-loaderは元々コンパイル速度が遅いというts-loaderの弱みを補うために開発されたみたいですが、現状ts-loaderがだいぶ改善されてきており変える理由がないのでts-loaderのままでいきます

**Comment by bokusunny** [comment]
css modulesの導入を #36 でやっているならこのissueはcloseしていいかな？

**Comment by rechtburg** [comment]
いや、やってないよ。

**Comment by bokusunny** [comment]
そうか。
多分パッケージとかもいらないしすぐできそうだからformとかの方でcss-modules試してみてくれないかな。

**Comment by bokusunny** [comment]
https://github.com/gajus/react-css-modules#whats-the-problem
こういうのもあるけど入れなくていいと思う。

**Comment by bokusunny** [comment]
これは #36 の時点で既に完了している。
